assignment 1
ACM-NITK/Machine-Learning-SMP-2019 pull request #23
Opened 2019-05-23 15:07 UTC by chandravaran

there is a text file for third question

2019-05-25 10:44 UTC, YashasG98 requested changes
- Your submission for question 8 is wrong, just check it again
- Also, the final points table you submitted doesn't seem to be using this dataset, if you have used some other dataset, try to translate the same steps onto the given dataset
- Send a PR with these changes

2019-05-25 10:58 UTC, chandravaran commented
Ok I will do that

On Sat, 25 May 2019, 16:14 Yashas G, <notifications@github.com> wrote:

> *@YashasG98* requested changes on this pull request.
>
>    - Your submission for question 8 is wrong, just check it again
>    - Also, the final points table you submitted doesn't seem to be using
>    this dataset, if you have used some other dataset, try to translate the
>    same steps onto the given dataset
>    - Send a PR with these changes
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ACM-NITK/Machine-Learning-SMP-2019/pull/23?email_source=notifications&email_token=AMAUUD5XKEXJH66DRZEZBITPXEJ73A5CNFSM4HPHAPT2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOBZWJWRQ#pullrequestreview-241998662>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMAUUDYA63CMNYONZTQGB3TPXEJ73ANCNFSM4HPHAPTQ>
> .
>

2019-05-27 10:32 UTC, chandravaran commented
i have used the data base given and fixed other problems

2019-05-28 10:54 UTC, YashasG98 approved these changes

2019-05-28 10:55 UTC, merged